'use client'

import { useState } from 'react'
import {
  Activity, AudioLines, Box, Bot, Check, ChevronDown, ChevronRight, CircleHelp, Cloud,
  Code2, Cpu, FileClock, Folder, Gauge, Globe2, LayoutGrid, Menu, Mic2, Play,
  Plus, Radio, Search, Settings2, ShieldCheck, Sparkles, Store, TestTube2, Upload, Users, X,
} from 'lucide-react'

const navigation = ['DASHBOARD', 'PROJECTS', 'TOOLS', 'ENGINES', 'CONNECTIONS', 'MARKETPLACE', 'AUDIT LOG', 'MEMORY SLABS', 'SETTINGS']
const apps = ['Vercel', 'Figma', 'Canva', 'OpenAI', 'Codex', 'Replit', 'Hugging Face', 'Lovable', 'Jotform', 'Linear', 'Notion', 'Ramp', 'PostHog', 'Supabase', 'Descript', 'SharePoint', 'Outlook Calendar']
const timeline = ['VIDEO', 'DIALOGUE', 'FOLEY', 'MUSIC', 'SFX']

export default function Page() {
  const [tab, setTab] = useState('CHARACTERS')
  const [menu, setMenu] = useState(false)
  const [toast, setToast] = useState('')
  const [query, setQuery] = useState('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }

  return (
    <main className="terminal-shell">
      <header className="terminal-header">
        <button className="terminal-brand" onClick={() => notify('APEX Terminal home')}><span className="apex-symbol">A</span><span><strong>APEX TERMINAL</strong><small>REAL-TIME ENGINE</small></span></button>
        <div className="terminal-search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="GABBY, WHAT ARE WE BUILDING?" /><AudioLines size={22} className="wave-icon" /></div>
        <div className="terminal-user"><span className="verified"><Check size={14} /> VERIFIED</span><span className="time">9:41 PM</span><button className="owner-avatar" aria-label="Open owner menu">AR</button><span className="owner"><strong>GODSPEED</strong><small>OWNER</small></span><ChevronDown size={16} /></div>
        <button className="mobile-menu" onClick={() => setMenu(!menu)} aria-label="Open menu"><Menu size={20} /></button>
      </header>

      <div className="terminal-grid">
        <aside className={`terminal-nav ${menu ? 'is-open' : ''}`}><div className="panel-label">WORKSPACE</div>{navigation.map((item, index) => <button key={item} className={`nav-item ${index === 0 ? 'active' : ''}`} onClick={() => notify(`${item} workspace selected`)}>{[LayoutGrid, Folder, Code2, Cpu, Cloud, Store, FileClock, ShieldCheck, Settings2].map((Icon, i) => i === index ? <Icon key={item} size={16} /> : null)}<span>{item}</span></button>)}</aside>

        <aside className="connected-panel"><div className="panel-title"><strong>CONNECTED APPS</strong><span>ALL SYSTEMS VERIFIED</span></div><div className="app-list">{apps.map((app) => <button key={app} className="connected-app" onClick={() => notify(`${app} connection verified`)}><span className="app-glyph">{app.slice(0, 1)}</span><span>{app}</span><i /></button>)}</div></aside>

        <section className="studio-panel"><div className="studio-title"><strong>3D CREATION STUDIO</strong><div className="studio-tabs">{['CREATE', 'CHARACTERS', 'WORLDS', 'ANIMATION', 'RENDER'].map((item) => <button key={item} className={tab === item ? 'selected' : ''} onClick={() => setTab(item)}>{item}</button>)}</div></div><div className="studio-stage"><div className="tool-rail">{[Sparkles, Box, Radio, Upload, Activity, AudioLines, Globe2, Gauge].map((Icon, index) => <button key={index} onClick={() => notify('Studio tool selected')}><Icon size={17} /></button>)}</div><div className="character-frame"><div className="frame-grid" /><div className="character-art"><div className="character-head" /><div className="character-body" /><div className="character-jacket" /><div className="character-chain" /></div><span className="frame-caption">CHARACTER / G-01</span></div><div className="asset-column"><div className="turntable"><div className="mini-character" /><div className="turntable-label">GODSPEED / FULL BODY</div></div><div className="material-grid">{['#1d2023','#68442f','#9d7141','#252c31','#101820','#46332a','#321d1a','#225d75'].map((color) => <button key={color} style={{ background: color }} onClick={() => notify('Material applied')} />)}</div></div></div><div className="studio-toolbar">{['SCULPT', 'MODEL', 'TEXTURE', 'RIG', 'ANIMATE', 'LIGHT', 'RENDER'].map((item, index) => <button key={item} onClick={() => notify(`${item} tool opened`)}>{[Sparkles, Box, Upload, Activity, Radio, Cloud, Play][index] && (() => { const Icon = [Sparkles, Box, Upload, Activity, Radio, Cloud, Play][index]; return <Icon size={15} /> })()}{item}</button>)}</div></section>

        <aside className="right-stack"><section className="gabby-terminal"><div className="right-title cyan">CONCIERGE: GABBY</div><div className="gabby-portrait"><div className="portrait-face" /><p>All systems online.<br />What are we<br />building tonight?</p></div><div className="gabby-actions"><button onClick={() => notify('New project ready')}>NEW PROJECT</button><button onClick={() => notify('Project browser opened')}>OPEN PROJECT</button></div></section><section className="project-status"><div className="right-title">PROJECT: GODSPEED</div><strong>STATUS: VERIFIED</strong><div className="progress"><span /></div><small>87%</small></section><section className="engine-panel"><div className="right-title">ENGINES</div><div className="engine-grid">{[['APEX ENGINE','REAL-TIME',Sparkles],['APEX RENDER','PHOTOREAL',Cloud],['PHYSICS','ADVANCED',Activity],['AUDIO ENGINE','SPATIAL',AudioLines],['AI GENERATION','MULTI-MODEL',Bot],['WORLD BUILDER','PROCEDURAL',Globe2]].map(([name, sub, Icon]) => <button key={name as string} onClick={() => notify(`${name} online`)}><Icon size={19} /><span><strong>{name as string}</strong><small>{sub as string}</small></span></button>)}</div></section></aside>
      </div>

      <div className="bottom-grid"><section className="system-panel"><div className="bottom-title">SYSTEM STATUS</div>{[['CPU','23%'],['GPU','41%'],['RAM','62%'],['VRAM','48%'],['NET','12.4 Mb/s']].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><i><b /></i><strong>{value}</strong></div>)}</section><section className="foley-panel"><div className="bottom-title">FOLEY & SOUND DESIGN <span>00:01:23.456</span></div><div className="waveform">{Array.from({ length: 42 }).map((_, i) => <i key={i} style={{ height: `${18 + ((i * 17) % 45)}%` }} />)}</div><div className="sound-list"><span>FOOTSTEPS_CONCRETE <b>0:03</b></span><span>CLOTH_RUSTLE <b>0:02</b></span><span>METAL_CLINK <b>0:01</b></span><span>WHOOSH_WIND <b>0:02</b></span><span>DOOR_OPEN <b>0:02</b></span></div><div className="panel-actions"><button onClick={() => notify('Recording started')}><Mic2 size={14} /> RECORD</button><button onClick={() => notify('Edit mode enabled')}>EDIT</button><button onClick={() => notify('Mix console opened')}>MIX</button><button onClick={() => notify('Mastering started')}>MASTER</button></div></section><section className="dialogue-panel"><div className="bottom-title">AI DIALOGUE & ADAK</div><div className="dialogue-row"><div className="dialogue-avatar"><div className="character-head small" /></div><div className="dialogue-bubbles"><span>What&apos;s the mission<br />tonight, boss?</span><span>Generate variations<br />with attitude.</span></div></div><div className="dialogue-wave waveform">{Array.from({ length: 30 }).map((_, i) => <i key={i} style={{ height: `${15 + ((i * 23) % 55)}%` }} />)}</div><div className="panel-actions"><button className="primary" onClick={() => notify('ADAK generation started')}>GENERATE</button><button onClick={() => notify('Voice clone opened')}>VOICE CLONE</button><button onClick={() => notify('ADAK flow opened')}>ADAK FLOW</button></div></section><section className="timeline-panel"><div className="bottom-title">TIMELINE / SEQUENCE</div><div className="time-ruler">00:00 <span>00:15</span><span>03:30</span><span>00:45</span><span>01:00</span></div>{timeline.map((item, index) => <div className="timeline-row" key={item}><span>{item}</span><i className={`clip clip-${index}`} /></div>)}</section><section className="audit-panel"><div className="bottom-title">AUDIT FEED <span>(REAL-TIME)</span></div>{['Project Loaded: GODSPEED','Memory Slab Verified','Character Loaded','Animation Applied','Foley Recorded','ADAK Generated','Render Started','Frame Verified','All Systems Go'].map((item, i) => <div className="audit-row" key={item}><Check size={12} /><span>9:4{i}:2{1 + i} PM</span>{item}</div>)}<button className="clear-button" onClick={() => notify('Audit feed cleared')}>CLEAR</button></section></div>

      <footer className="terminal-footer"><div className="footer-actions">{[['BUILD',Code2],['RUN',Play],['TEST',TestTube2],['VERIFY',ShieldCheck],['DEPLOY',Upload],['PUBLISH',Store]].map(([label, Icon]) => <button key={label as string} onClick={() => notify(`${label} action selected`)}><Icon size={16} />{label as string}</button>)}</div><div className="footer-apex"><span>APEX</span><small>REAL-TIME ENGINE</small></div><div className="footer-state"><span className="truth"><ShieldCheck size={24} /> <b>TRUTH: VERIFIED<small>ALL SYSTEMS OPERATIONAL</small></b></span><span className="gabby-state"><Mic2 size={22} /> <b>GABBY ONLINE<small>AI CONCIERGE ACTIVE</small></b><AudioLines size={25} /></span></div></footer>
      {toast && <div className="terminal-toast"><Check size={15} />{toast}</div>}
    </main>
  )
}
